version: '3'

services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - '3001:3001'

  frontend:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - '3000:80'
